stages:
  - build

variables:
  RUSTFLAGS: "-D warnings"

clippy:
  stage: build
  image: rustlang/rust:nightly
  script:
    - cargo clippy

fmt:
  stage: build
  image: rustlang/rust:nightly
  script:
    - cargo fmt --check

rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  script:
    - cargo build --verbose
    - cargo test --verbose
