variables:
  PACKAGE_NAME: qad
  CARGO_HOME: "$CI_PROJECT_DIR/.cargo"
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${PACKAGE_NAME}/${CI_COMMIT_TAG}/${PACKAGE_NAME}"

include:
  - local: '/cicd/test.gitlab-ci.yml'
  - local: '/cicd/release.gitlab-ci.yml'

stages:
  - test
  - release

cache: &global_cache
  key: one-key-to-rule-them-all
  paths:
    - .cargo/
    - target/
  policy: pull

build:
  image: rust:latest
  stage: release
  script:
    - cargo build --release
    - test "$CI_COMMIT_TAG" == "$(target/release/${PACKAGE_NAME} --version)"
    - mkdir bin
    - cp target/release/${PACKAGE_NAME} bin/${PACKAGE_NAME}
  artifacts:
    paths:
      - bin
  rules:
    - if: $CI_COMMIT_TAG
  cache:
    <<: *global_cache
    policy: pull-push
