variables:
  RUSTFLAGS: "-D warnings"

clippy:
  image: rustlang/rust:nightly
  script:
    - cargo clippy

fmt:
  image: rustlang/rust:nightly
  script:
    - cargo fmt --check

rust-nightly:
  image: rustlang/rust:nightly
  script:
    - cargo build --verbose
    - cargo test --verbose

shellcheck:
  image: koalaman/shellcheck-alpine:stable
  script: find -name '*.sh' -type f -exec shellcheck {} '+'

test-autocomplete:
  image: bash
  script:
    - tools/bash-unit-tests.sh
