[package]
name = "dt"
version = "0.2.2"
edition = "2021"

[dependencies]
argh = "0.1.4"
term = "0.7.0"
atty = "0.2.11"
regex = "1.5.4"
toml = "0.5.8"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.8.23"
yaml-rust = "0.4.5"
