[package]
name = "qad"
version = "0.6.0"
edition = "2021"

[dependencies]
anyhow = "1.0.56"
argh = "0.1.4"
atty = "0.2.11"
indexmap = "1.8.0"
regex = "1.5.4"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.8.23"
terminal_size = "0.1.17"
yaml-rust = "0.4.5"
