
build-packages:
  stage: release
  image: rust:latest
  needs:
    - build
  rules:
    - if: $CI_COMMIT_TAG
  before_script:
    - cargo install cargo-deb cargo-generate-rpm
    - rustup target add x86_64-unknown-linux-musl
  script:
    - bin/qad autocomplete > /tmp/qad.bash
    - cargo deb --target x86_64-unknown-linux-musl --output target/release/${PACKAGE_NAME}.deb
    - cargo generate-rpm --output target/release/${PACKAGE_NAME}.rpm
  artifacts:
    paths:
      - target/release/${PACKAGE_NAME}.deb
      - target/release/${PACKAGE_NAME}.rpm

upload binary:
  stage: release
  needs:
    - build
    - build-packages
  image: curlimages/curl:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - 'curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file bin/${PACKAGE_NAME} ${PACKAGE_REGISTRY_URL}'
    - 'curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file target/release/${PACKAGE_NAME}.deb ${PACKAGE_REGISTRY_URL}.deb'
    - 'curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file target/release/${PACKAGE_NAME}.rpm ${PACKAGE_REGISTRY_URL}.rpm'

changelog:
  stage: release
  image: alpine
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - apk add bash git
    - printf 'CHANGELOG=%s\n' "$(./tools/changelog --format web)" > description.env
  artifacts:
    reports:
      dotenv: description.env

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - upload binary
    - changelog
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "releasing ${PACKAGE_NAME}..."
    - echo $CHANGELOG
  release:
    name: 'Release $CI_COMMIT_TAG'
    description: '$CHANGELOG'
    tag_name: '$CI_COMMIT_TAG'
    ref: '$CI_COMMIT_TAG'
    assets:
      links:
        - name: '${PACKAGE_NAME}-${CI_COMMIT_TAG}'
          url: "${PACKAGE_REGISTRY_URL}"
          link_type: other
        - name: '${PACKAGE_NAME}-${CI_COMMIT_TAG}.deb'
          url: "${PACKAGE_REGISTRY_URL}.deb"
          link_type: package
        - name: '${PACKAGE_NAME}-${CI_COMMIT_TAG}.rpm'
          url: "${PACKAGE_REGISTRY_URL}.rpm"
          link_type: package
