clippy:
  image: rustlang/rust:nightly
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME'
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == ""'
  script:
    - cargo clippy --tests --color=always

lint-commits:
  image: node
  cache: []
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME'
  script:
    - npm install -g @commitlint/config-conventional @commitlint/cli
    - commitlint --from=$CI_MERGE_REQUEST_DIFF_BASE_SHA --to=$CI_COMMIT_SHORT_SHA

fmt:
  image: rustlang/rust:nightly
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME'
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == ""'
  script:
    - cargo fmt --check

rust-nightly:
  image: rustlang/rust:nightly
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME'
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == ""'
  script:
    - cargo test -- --color=always

shellcheck:
  image: koalaman/shellcheck-alpine:stable
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME'
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == ""'
  script: find -name '*.sh' -not -path '*/.*' -not -path '*/target/*' -type f -exec shellcheck {} '+'

test-autocomplete:
  image: bash
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME'
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == ""'
  script:
    - tools/bash-unit-tests.sh
