#!/usr/bin/env bash

set -euo pipefail

latest_tag=$(git tag --no-contains HEAD | tail -n 1)

format=
while (($#)); do
  case "$1" in
  --format)
    format=$2
    shift
    ;;
  esac
  shift
done

mapfile -t commits < <(git log "$latest_tag..HEAD" --format="%s" --no-merges)

{
if [ "$format" == "web" ]; then
  printf -- "%s<br>" "${commits[@]}"
else
  printf -- "%s\n" "${commits[@]}"
fi
} | grep -E '^(feat|fix|docs|perf|prune|ci)'
